builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 1
    minor: 0

stages:
  build:
    image: golang:1.17-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
      API_BASE_URL: estafette.secret(h-J_d2FmKMlNY355.vA_kcSVAL9d1Zzkuzksp7FAEw0kVHsNNa2JypaJealuDm8glOgvIvC5wyiywF9MMJjZgtvGKeEanSJnr.sxLkaSMYLpt_eWIq21o8_lBew0NVF9lXbSp-v6JeNVaL2o4wJg3XuzFzySzNvMh8qtmxph-xRq-VODCsDZzXJ7W1e39C)
      CLIENT_ID: estafette.secret(5NR4yaVd8MR8nLio.8A8xs8jm9tr9iX-phQLHQ-3blrlJ21Lk-prvx02Xp3c7M9e8VUaYinAgtPVsAdxFKBsS_A==.9lJ87N684IC_3DaokFuSFLjOz74FjkW9o8rogliTvSBleIi-n8ZClzqxM8TUki8a_TGlr0Hff_9gsCWHdvmENRNaLM-j)
      CLIENT_SECRET: estafette.secret(DqDyZ-RJFDT1lpwC.JlrbxN1yHKkqds1srfNfHoDkq8UAdrXKgnV9WYK1NJx8elm54KQ_AKQkvkSY1nn8XlTW_Jt-gqUKTMZSUWEHSAJphPxAXNXlvTrd_3636Nk=.dmb_mep-S6wHS5o_tLNrLITJlvBuZ6z9sHB_SK-fTqYtIkKy_o0lK5k5kB-9jmn2c3P3rKc_TlZ1s1Cf8Dp3YS9Jn3LJ)
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="${ESTAFETTE_GIT_NAME} is an application to clean up hanging jobs"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  tag-revision:
    image: golang:1.17-alpine
    commands:
    - apk add git
    - git tag ${ESTAFETTE_BUILD_VERSION}
    - git push origin ${ESTAFETTE_BUILD_VERSION}

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'failed'