{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estafette-ci-hanging-job-cleaner.fullname" . }}
  labels:
{{ include "estafette-ci-hanging-job-cleaner.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - list
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - list
  - delete
{{- end -}}